#-------------------------------------------------------------------------------
#
# Location Reference Service
#
# Centralizes all the logic for encoding, checking, and parsing location
# references within TransAM. This method is mainly used for assets and other classes
# that implement TransamGeolocatble
#
# A location reference can be any format that is supported by the geocoder that
# is configured. The standard formats that are supported by *all* geocoders are
#
#     address
#     coordinate
#     well_known_text
#
# All geocoder services need to implement the parse_xxxx method for each non-standard
# LRS format, for example if there were a ROUTE_MILEPOINT LRS type the geocoder
# would need to implement parse_route_milepoint() and parse_address() to parse an
# address string
#
#-------------------------------------------------------------------------------
class LocationReferenceService

  # The geocoder to use comes from the Rails config
  GEOCODING_SERVICE = Rails.application.config.geocoding_service

  #-----------------------------------------------------------------------------
  # Inputs
  #-----------------------------------------------------------------------------
  # the raw (input) location reference
  attr_accessor :location_reference
  # the format used to interpret the location reference
  attr_accessor :format

  #-----------------------------------------------------------------------------
  # Outputs
  #-----------------------------------------------------------------------------
  # the geometry returned, if any
  attr_reader   :geometry
  # the standardized/formatted location reference
  attr_reader   :formatted_location_reference
  # an array of errors generated by this service or by the geocoder
  attr_accessor :errors
  # an array of warnings from the geocoder service
  attr_accessor :warnings

  #-----------------------------------------------------------------------------
  # Configurations
  #-----------------------------------------------------------------------------
  # the GIS service used to encode geometries from the results of a geocode
  attr_reader   :gis_service
  # the Geocoding service used to geocode the location references
  attr_reader   :geocoding_service
  # the name of the geometry column to set the geometry
  attr_accessor :column_name
  # the class that the geometry is being assigned to. Only needed for georuby
  # adapters
  attr_accessor :klass

  #-----------------------------------------------------------------------------

  #-----------------------------------------------------------------------------
  # Returns true if the parser has errors
  def has_errors?
    @errors.present?
  end

  #-----------------------------------------------------------------------------
  # Parses a location reference. This method simply delegates the processing to
  # the geocoder that has been configured. The method called is constructed from
  # the location reference type (format). If the method is not supported by the
  # geocoder, an error is generated
  def parse(locref, format)
    Rails.logger.debug "parse '#{locref}', format = '#{format}'"
    # reset the current state
    reset
    @location_reference = locref
    @format = format

    # the method signature defaults to parse_xxx where xxx is the name of the
    # LRS format.
    parse_method = "parse_#{format.downcase}"
    if @geocoding_service.respond_to? parse_method
      method_object = @geocoding_service.method parse_method
      method_object.call @location_reference

      # process the results. If errors were generated then we add them to this
      # list of errors
      if @geocoding_service.has_errors?
        @geocoding_service.errors.each do |e|
          @errors << e
        end
      else
        # propagate any warnings from the service to this instance
        @geocoding_service.warnings.each {|x| @warnings << x}
        # construct a geometry if we have coordinates
        if @geocoding_service.coords.present?
          # if a single pair create a point
          if @geocoding_service.coords.count == 2
            @geometry = @gis_service.as_point(@geocoding_service.coords.first, @geocoding_service.coords.last)
          elsif @geocoding_service.coords.count > 2
            # otherwise create a linestring
            @geometry = @gis_service.as_linestring(@geocoding_service.coords)
          end
        end
        # cache the canoical representation of the address, if one is provided
        @formatted_location_reference = @geocoding_service.formatted_location_reference
      end
    else
      @errors << "Geocoder method #{parse_method} is not supported for geocoding service #{GEOCODING_SERVICE}"
    end

    @errors.empty?
  end
  #-----------------------------------------------------------------------------
  # Initialize, a hash of options can be added in
  def initialize(attrs = {})
    # reset the current state
    reset

    attrs.each do |k, v|
      self.send "#{k}=", v
    end

    # initialize the gis service sending the object class
    @gis_service = GisService.new({:klass => @klass, :column_name => @column_name})

    # initialize the geocoding service based on the Rails config
    @geocoding_service = GEOCODING_SERVICE.constantize.new

  end


  #-----------------------------------------------------------------------------
  protected
  #-----------------------------------------------------------------------------

  def reset
    @geometry = nil
    @formatted_location_reference = nil
    @errors = []
    @warnings = []
  end

end
