language: ruby
rvm:
- 2.2.2
branches:
  only:
  - master
before_install:
- sudo apt-get update
- gem update bundler
- sudo apt-get install libgeos-dev libproj-dev
- mysql -e "create database IF NOT EXISTS transam_spatial_testing;" -uroot
addons:
  code_climate:
    repo_token: ce7c157104b0cf1f2babf66d9cc10bbe598607781e8eeb1ba1593fec1d1fc5c1
before_script:
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake app:transam_spatial:prepare_rspec
- bundle exec rspec
