#database.travis.yml

# sqlite: &sqlite
#   adapter: sqlite3
#   database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2rgeo
  username: root
  password:
  database: transam_spatial_testing

# postgresql: &postgresql
#   adapter: postgresql
#   username: postgres
#   password:
#   database: strano_<%= Rails.env %>
#   min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults